[package]
name = "pleb_ui"
version = "0.1.0"
authors = ["Michael Eden <themichaeleden@gmail.com>"]

[dependencies]
alsa-sys = "0.0.8"

[dependencies.notify-rust]
git = "https://github.com/illegalprime/notify-rust.git"
