[package]
name = "pleb_ui"
version = "0.1.0"
authors = ["Michael Eden <themichaeleden@gmail.com>"]

[dependencies]
alsa-sys = "0.0.8"
notify-rust = "3.1.1"
ears = "0.3.4"
dbus = "0.3.2"

[dependencies.xcb]
version = "0.7"
features = ["randr"]
